export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_ERROR = 'GET_QUESTIONS_ERROR';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';
